# Generated by Django 5.0.6 on 2024-06-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectmodule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodule',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not Started'), (1, 'In Progress'), (2, 'Completed'), (3, 'Cancelled')], default=0),
        ),
    ]
